[package]
name = "aws_sdk_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "1.0.3"
aws-sdk-dynamodb = "1.4.0"
tokio = { version = "1.34.0", features = ["full"] }
